<Project>
  <ItemGroup>
    <!-- Application -->
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageVersion Include="Serilog" Version="4.4.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="System.CommandLine" Version="2.0.12" />

    <!-- Testing -->
    <PackageVersion Include="AwesomeAssertions" Version="9.6.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="Serilog.Sinks.InMemory" Version="2.0.0" />
    <PackageVersion Include="Serilog.Sinks.InMemory.Assertions" Version="2.0.0" />
    <PackageVersion Include="Serilog.Sinks.XUnit.Injectable" Version="4.0.271" />
    <PackageVersion Include="WireMock.Net" Version="2.16.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>
</Project>
