<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GrillMaster.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrossCutting\CrossCutting.csproj" />
    <ProjectReference Include="..\GrillMaster.Domain\GrillMaster.Domain.csproj" />
  </ItemGroup>

</Project>
